import ExcelJS from "exceljs";
import { tryGetFactor } from "../cbam/factors";
import type { DeclarationResult } from "../cbam/declaration";
import { ROUTE_INDICATORS } from "../cbam/regulatory";
import type { PrecursorActivity } from "../cbam/types";
import type { WorkspaceState } from "../workspace/types";
import { workspaceActivities } from "../workspace/declaration";

/**
 * The operator's emissions report as a workbook.
 *
 * Sheets follow the sections of the Commission's communication template for
 * installations (A_InstData, B_EmInst, D_Processes, E_PurchPrec,
 * Summary_Products, Summary_Communication) so a declarant or verifier finds
 * each figure where they expect it. It is not the Commission's own file: the
 * values can be copied into the official template, and the Summary sheet says
 * so.
 */

type Row = (string | number | null | undefined)[];

function sheet(wb: ExcelJS.Workbook, name: string, title: string, header: string[], rows: Row[]) {
  const ws = wb.addWorksheet(name);
  ws.addRow([title]).font = { bold: true, size: 13 };
  ws.addRow([]);
  const h = ws.addRow(header);
  h.font = { bold: true };
  h.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE8ECF2" } };
  for (const r of rows) ws.addRow(r.map((v) => (v === undefined ? null : v)));
  ws.columns.forEach((c, i) => {
    const values = [header[i] ?? "", ...rows.map((r) => String(r[i] ?? ""))];
    c.width = Math.min(60, Math.max(10, ...values.map((v) => v.length + 2)));
  });
  ws.views = [{ state: "frozen", ySplit: 3 }];
  return ws;
}

export async function emissionsReportXlsx(
  d: DeclarationResult,
  state: WorkspaceState,
  meta: { workspaceName: string; generatedBy: string },
): Promise<Uint8Array> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "CarbonPass";
  wb.created = new Date(d.computedAt);
  const inst = d.installation;

  // ------------------------------------------------------------- Summary
  const summary = wb.addWorksheet("Summary");
  summary.addRow(["CBAM operator emissions report"]).font = { bold: true, size: 14 };
  summary.addRow([`${inst.name} - ${inst.operator}`]);
  summary.addRow([`Reporting period ${d.period.start} to ${d.period.end} (${d.period.year})`]);
  summary.addRow([]);
  const kv: [string, string | number][] = [
    ["Workspace", meta.workspaceName],
    ["Generated", d.computedAt],
    ["Generated by", meta.generatedBy],
    ["Direct emissions of the installation (tCO2e)", round(d.totals.directT, 1)],
    ["Indirect emissions of the installation (tCO2e)", round(d.totals.indirectT, 1)],
    ["Embedded in bought-in precursors (tCO2e)", round(d.totals.precursorT, 1)],
    ["Goods produced (t)", round(d.totals.goodsT, 1)],
    ["Of which to the EU (t)", round(d.totals.goodsEuT, 1)],
    ["EU-bound embedded emissions counted (tCO2e)", round(d.totals.obligationT, 1)],
    ["Free allocation adjustment (tCO2e)", round(d.exposure.freeAllocationAdjustmentT, 1)],
    ["CBAM certificates implied", round(d.exposure.netCertificates, 1)],
    ["Certificates on default values instead", round(d.exposure.defaultScenario.certificates, 1)],
    ["CBAM factor / CSCF", `${d.sefa.cbamFactor} / ${d.sefa.cscf}`],
    ["Readiness", `${d.readiness.score}/100 (${d.readiness.band})`],
    ["Open blockers / warnings", `${d.readiness.blockers} / ${d.readiness.warnings}`],
  ];
  for (const [k, v] of kv) summary.addRow([k, v]);
  summary.addRow([]);
  summary.addRow(["Sources"]).font = { bold: true };
  for (const s of Object.values(d.sources)) {
    summary.addRow([
      `${s.act} - ${s.title}`,
      `${s.version}${s.sha256 ? ` (sha256 ${s.sha256.slice(0, 16)}...)` : ""}`,
    ]);
  }
  summary.addRow([]);
  summary.addRow([
    "This workbook follows the structure of the Commission's communication template for installations. " +
      "It is not the official template file; transfer the values into the current official template where a declarant requires it.",
  ]);
  summary.addRow([d.disclaimer]);
  summary.getColumn(1).width = 52;
  summary.getColumn(2).width = 48;

  // ----------------------------------------------------------- A_InstData
  sheet(
    wb,
    "A_InstData",
    "Installation data",
    ["Field", "Value"],
    [
      ["Name of the installation", inst.name],
      ["Operator", inst.operator],
      ["Street, number", inst.street],
      ["City", inst.city],
      ["State / region", inst.state],
      ["Postcode", inst.postcode],
      ["Country", inst.country],
      ["UN/LOCODE", inst.unlocode ?? ""],
      ["Latitude of main emission source", inst.latitude ?? ""],
      ["Longitude of main emission source", inst.longitude ?? ""],
      ["Economic activity", inst.economicActivity ?? ""],
      ["CBAM Registry operator id", inst.registryOperatorId ?? ""],
      ["Contact", `${inst.contactName} <${inst.contactEmail}>`],
      ["Reporting period start", d.period.start],
      ["Reporting period end", d.period.end],
    ],
  );

  // ------------------------------------------------------------- B_EmInst
  const streams: Row[] = [];
  for (const e of d.emissions) {
    const groups = [
      ["Combustion", e.contributions.fuel],
      ["Process material", e.contributions.processMaterial],
      ["Electricity (indirect)", e.contributions.electricity],
      ["Measurable heat", e.contributions.heat],
    ] as const;
    for (const [type, items] of groups) {
      const byLabel = new Map<
        string,
        {
          q: number;
          unit: string;
          tj: number;
          em: number;
          factor: string;
          tier: string;
          source: string;
        }
      >();
      for (const c of items) {
        const f = tryGetFactor(c.factorId);
        const cur = byLabel.get(c.label) ?? {
          q: 0,
          unit: c.quantityUnit,
          tj: 0,
          em: 0,
          factor: `${c.factorValue} ${c.factorUnit}`,
          tier: f ? String(f.tier) : "",
          source: c.reference ?? (f ? `${f.source} (${f.vintage})` : ""),
        };
        cur.q += c.quantity;
        cur.tj += c.energyTJ ?? 0;
        cur.em += c.emissionsT;
        byLabel.set(c.label, cur);
      }
      for (const [label, v] of byLabel) {
        streams.push([
          e.processName,
          type,
          label,
          round(v.q, 3),
          v.unit,
          v.tj ? round(v.tj, 3) : "",
          v.factor,
          v.tier,
          v.source,
          round(v.em, 2),
        ]);
      }
    }
  }
  sheet(
    wb,
    "B_EmInst",
    "Source streams and emissions",
    [
      "Process",
      "Type",
      "Source stream",
      "Activity data",
      "Unit",
      "Energy (TJ)",
      "Factor",
      "Factor tier",
      "Factor source",
      "tCO2e",
    ],
    streams,
  );

  // ----------------------------------------------------------- D_Processes
  const sefaByProcess = new Map(d.sefa.goods.map((g) => [g.processId, g]));
  sheet(
    wb,
    "D_Processes",
    "Production processes",
    [
      "Process",
      "Aggregated goods category",
      "Route",
      "Benchmark route",
      "Activity level (t)",
      "Direct attributed (tCO2e)",
      "Indirect attributed (tCO2e)",
      "Bought-in precursors (tCO2e)",
      "On-site precursors (tCO2e)",
      "Process benchmark BM* (col. A)",
      "SFA process (tCO2e/t)",
      "Lowest tier",
      "Uncertainty (direct)",
    ],
    d.emissions.map((e) => {
      const p = inst.processes.find((x) => x.id === e.processId);
      const s = sefaByProcess.get(e.processId);
      return [
        e.processName,
        e.category,
        e.route ?? "",
        p?.benchmarkRoute
          ? `${p.benchmarkRoute} - ${ROUTE_INDICATORS[p.benchmarkRoute] ?? ""}`
          : "",
        round(e.activityLevelT, 2),
        round(e.directT, 2),
        round(e.indirectT, 2),
        round(e.precursorDirectT + e.precursorIndirectT, 2),
        round(e.internalPrecursorDirectT + e.internalPrecursorIndirectT, 2),
        s?.benchmark
          ? `${s.benchmark.value}${s.benchmark.indicator ? ` (${s.benchmark.indicator})` : ""}`
          : "",
        s ? round(s.sfaProc, 6) : "",
        e.lowestTier,
        `${(e.directUncertainty * 100).toFixed(1)}%`,
      ];
    }),
  );

  // ----------------------------------------------------------- E_PurchPrec
  const activities = workspaceActivities(state);
  const resolutions = Object.assign(
    {},
    ...d.emissions.map((e) => e.precursorResolutions),
  ) as Record<string, DeclarationResult["emissions"][number]["precursorResolutions"][string]>;
  const precursorRows: Row[] = activities
    .filter((a): a is PrecursorActivity => a.kind === "precursor")
    .filter((a) => !d.excludedActivityIds.includes(a.id))
    .map((a) => {
      const r = resolutions[a.id];
      return [
        a.periodStart.slice(0, 7),
        inst.processes.find((p) => p.id === a.processId)?.name ?? a.processId,
        a.cnCode,
        a.supplierName ?? "",
        a.originCountry ?? "unknown",
        round(a.quantityT, 3),
        r?.status ?? "",
        r ? round(r.seeDirect, 4) : "",
        r ? round(r.seeIndirect, 4) : "",
        r?.reference ?? "",
        r ? round(r.sefa, 4) : "",
        r?.sefaReference ?? "",
        `${a.lineage.fileName} row ${a.lineage.row}`,
      ];
    });
  sheet(
    wb,
    "E_PurchPrec",
    "Purchased precursors",
    [
      "Month",
      "Consuming process",
      "CN code",
      "Supplier",
      "Country of production",
      "Quantity (t)",
      "Value source",
      "SEE direct",
      "SEE indirect",
      "Reference",
      "SEFA",
      "SEFA reference",
      "Source row",
    ],
    precursorRows,
  );

  // ------------------------------------------------------ Summary_Products
  sheet(
    wb,
    "Summary_Products",
    "Goods and specific embedded emissions",
    [
      "CN code",
      "Description",
      "Process",
      "Produced (t)",
      "To EU (t)",
      "Internal (t)",
      "SEE direct",
      "SEE indirect",
      "SEE total",
      "SEE counted",
      "SEFA",
      "Obligation per t",
      "Default value incl. mark-up",
      "vs default",
      "Tier",
      "Uncertainty",
    ],
    d.lines.map((l) => [
      l.cnCode,
      l.description,
      l.processName,
      round(l.quantityT, 2),
      round(l.quantityEuT, 2),
      round(l.quantityInternalT, 2),
      round(l.seeDirect, 6),
      round(l.seeIndirect, 6),
      round(l.seeTotal, 6),
      round(l.seeForObligation, 6),
      round(l.sefa, 6),
      round(Math.max(0, l.seeForObligation - l.sefa), 6),
      l.defaultSee !== undefined ? round(l.defaultSee, 4) : "",
      l.vsDefault !== undefined ? `${(l.vsDefault * 100).toFixed(1)}%` : "",
      l.lowestTier,
      `${(l.uncertainty * 100).toFixed(1)}%`,
    ]),
  );

  // -------------------------------------------------- Summary_Communication
  sheet(
    wb,
    "Summary_Communication",
    "Data for authorised CBAM declarants",
    [
      "CN code",
      "Description",
      "Production route",
      "SEE direct (tCO2e/t)",
      "SEE indirect (tCO2e/t)",
      "Counted",
      "SEFA (tCO2e/t)",
      "Carbon price paid",
    ],
    d.lines.map((l) => [
      l.cnCode,
      l.description,
      l.route ?? "",
      round(l.seeDirect, 6),
      round(l.seeIndirect, 6),
      l.directOnly ? "Direct only (Annex II)" : "Direct and indirect",
      round(l.sefa, 6),
      d.exposure.carbonPriceCredit > 0 ? "See evidence" : "None claimed",
    ]),
  );

  // ------------------------------------------------------------- Findings
  sheet(
    wb,
    "Findings",
    "Data-quality findings at the time of export",
    ["Code", "Severity", "Title", "Detail", "Remedy", "Reference", "Acknowledged"],
    d.findings.map((f) => [
      f.code,
      f.severity,
      f.title,
      f.detail,
      f.remedy,
      f.reference ?? "",
      f.acknowledged ? "yes" : "",
    ]),
  );

  const buffer = await wb.xlsx.writeBuffer();
  return new Uint8Array(buffer as ArrayBuffer);
}

function round(n: number, dp: number): number {
  const f = 10 ** dp;
  return Math.round(n * f) / f;
}
